name: "Rust Build"

on:
  push:
  pull_request:

jobs:
  rust-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: CfirTsabari/actions-rs-toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: nightly
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --locked --verbose
