name: "Rust Build"

on:
  push:
  pull_request:

jobs:
  rust-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Cargo leptos
        run: cargo install cargo-leptos

      - name: Build
        run: cargo leptos build
